image: java_openjdk7

env:
  - AWS_ACCESS_KEY_ID=$$AWS_ACCESS_KEY_ID
  - AWS_SECRET_ACCESS_KEY=$$AWS_SECRET_ACCESS_KEY
  - EC2_KEY_NAME=aldrin@leal.eng.br
  - AWSEB_S3_BUCKET=ingenieux-beanstalk-apps
  - SONAR_HOST=$$SONAR_HOST
  - SONAR_JDBC_PASSWORD=$$SONAR_JDBC_PASSWORD

script:
  - curl -sSL https://raw.github.com/ingenieux/mvm/master/install.sh | bash
  - source ~/.mvm/mvm.sh && mvm install 3.2.1 && mvm alias default 3.2.1
  - if [ ! -d "$HOME/.m2" ]; then mkdir .m2 ; fi
  - cp ci/settings.xml $HOME/.m2/settings.xml
  - mvn -f beanstalk-maven-plugin-it/pom.xml clean verify sonar:sonar -Dbeanstalk.project.name=mbit-drone -Prelease,it

#
#notify:
#  email:
#    recipients:
#      - brad@drone.io
#  gitter:
#    room_id: $$GITTER_ROOM
#    token: $$GITTER_KEY
#    on_started: false
#    on_success: true
#    on_failure: true
